### ISSUE TITLE
2020 TODO

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfCSS-2019#12]
- Add `font-display`
- `line-clamp`

**Comment by SachaG** [comment]
https://dev.to/ananyaneogi/css-can-do-that-18g7

**Comment by SachaG** [comment]
### CSS-in-JS

- https://github.com/callstack/linaria
- https://github.com/rofrischmann/fela

### CSS Frameworks

- http://getskeleton.com/
- https://picturepan2.github.io/spectre/
- https://github.com/inuitcss/inuitcss

**Comment by nucliweb** [comment]
### CSS Houdini

- https://github.com/nucliweb/awesome-css-houdini

**Comment by SachaG** [comment]
CSS Logical Properties
