### ISSUE TITLE
Translating the State of CSS Survey in your language

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfCSS-2019#30]
# The Workflow
If you’d like to help, here’s some more information about the workflow we’ve implemented. Let’s say Alicia wants to translate our results to Spanish.

### Starting a New Language

- Alicia forks this repo to her own GitHub account.
- She makes an initial commit modifying the languages files (see below for information on where to find them).
- She then opens a PR back to the root repo.
- In the PR description, she pastes in [this list of to-do items](https://gist.github.com/SachaG/0b28fcdf38d602ebf5ccd0cb0295fb0b) to help others see how far the translation has progressed.

### Contributing to an Existing Language

Now let’s say Javier comes along, and he wants to help with the Spanish translation effort. He would:

- Search the list of open PRs for any pending Spanish translations.
- Leave a comment on the PR asking for write access to Alicia’s fork (which can be given in the repo’s Settings > Collaborators & teams screen).
- Once Javier has write permissions, he can now add commits directly to the PR.

### Developing

For a language to appear in the dropdown, it needs to first be added to the `locales.yml` file. You can then run the Gatsby project with `gatsby develop`. 

### Finalizing a Language

Once a language is complete, Alicia can ask me (@SachaG) to review and merge the PR.

This means that the first person to start a new translation PR will become the “manager” for that language and be responsible with adding collaborators and notifying us once all collaborators are happy with the result.

### Language Files

Translation files are located in [/src/translations](https://github.com/StateOfJS/state-of-css-2019/tree/master/src/translations). Each language has the following files:

- A root `locale.yml` file (for exampe` fr-FR.yml`) containing all user interface translations.
- A `/locale` directory (for example `/fr-FR`) containing all markdown files for introductions, conclusions, etc.

When contributing new translations, please make sure you follow the same directory and file structure!

**Comment by leviding** [comment]
I'd like to help translate this survey to Chinese. I am the administrator of [a large English-Chinese translation organization in China](https://github.com/xitu/gold-miner). I have rich experience in translation and translation management. 🚀

**Comment by oliviel** [comment]
hello, 

I' m Oliviel, I will like to help with the translation to Spanish. I' am actually studying software engineering and I love front end development this is why I will like to help with the project.

P.S:  This will be my first contribution to an open source project.

My Email: olivielultimate@gmail.com

**Comment by ymcheung** [comment]
Hello, I would like to translate into Chinese (which is for people in Taiwan and Hong Kong.) I have been using CSS since CSS 2.1, and have translated around 40 great articles.

Translation publication: https://intersection.tw
Email: ymcheung.tw@gmail.com

**Comment by victoriavilasb** [comment]
Hi, I would like to translate into Portuguese. 
I'm a front-end developer and I have an experience working in a software internationalization.

**Email:** victoriaovilas@gmail.com

**Comment by sutangu** [comment]
Hello, I would like to translate it to Russian.

email: sutangu@gmail.com

**Comment by Kondratieva-Vecklenko** [comment]
I want to help you with the translation into Russian of information from your service. 
I am Graphic-design and css is my favorite style sheet language.

e-mail: natalie.veklenko@gmail.com

**Comment by S1ngS1ng** [comment]
Hey Sacha,
I worked on the translation of StateOfJS ([PR](https://github.com/StateOfJS/StateOfJS/pull/153)). Please let me know if you need help w/ the translation of StateOfCSS.

My email: liuxing0514@gmail.com

**Comment by ansenhuang** [comment]
Hello Sacha,

I'm Anson, it's would be a great honor if I have an opportunity to translate this survey into Chinese.
I'm a frontend developer and I have rich experience in both CSS and JavaScript, so I can definitely understand what you mean in the survey. In addition, I would like to add some ideas in my mind if it's possible. 
Please let me know if you have a decision. Here is my email: ancheng1992@126.com

**Comment by zmencay** [comment]
Hello, 

I´m an experienced front-end developer at CSS and semantic HTML, more than 15 years doing layout, templates, webs, and themes. I think the web can be very useful to Spanish people, so I want to translate to **Spanish**. 
Please keep me posted if you want to speak with me :)

zuri@synctc.com / @zmencay / https://es.linkedin.com/in/zurimenendez

Thnx a lot.

**Comment by SachaG** [comment]
Thanks to everybody who volunteered! I've updated the initial issue with detailed workflow instructions. Basically, one person needs to fork this repo and take charge of the translation effort for each language. Let me know if you have any questions!

**Comment by plouc** [comment]
Thank you everybody! We're currently finalizing a few things (like the Awards page), I think it's better if you wait a couple of days before starting to translate the survey. Sorry for that.

**Comment by Naturalclar** [comment]
Hello! I would like to help translating the survey to **Japanese**, once the page is ready to be translated.
I have some experience working on translation for several OSS projects, such as `ReactJS` `Bitrise` and `CircleCI`.

My Email: jesse.katsumata@gmail.com

**Comment by justiszley** [comment]
Could you please add some info on how to launch the website locally with the language one is translating into?
I've run `yarn run build` and gotten a folder with static files. I open one of HTMLs and can't change the language through selector element.
Is there a way to run it like the original site but on localhost? thanks!)
PS i've been always using npm and I am not acquainted with yarn, so if it is a matter of a single command please let me know. Thanks!

**Comment by SachaG** [comment]
@justiszley yes you got it, sorry! You need to add the language to `locales.yml`. And you can start the project with `gatsby develop` as well.

**Comment by SachaG** [comment]
OK, we've just pushed the awards and heatmaps, so the site is now complete! You can start translating :)

**Comment by orlovaleksandr** [comment]
Hi, I'd like to translate it to Russian.

email: orlov_a@tut.by

**Comment by inkcreativ** [comment]
HI, ready for French translation if needed. Regards

**Comment by rcarlosalba** [comment]
> 
> 
> hello,
> 
> I' m Oliviel, I will like to help with the translation to Spanish. I' am actually studying software engineering and I love front end development this is why I will like to help with the project.
> 
> P.S: This will be my first contribution to an open source project.
> 
> My Email: [olivielultimate@gmail.com](mailto:olivielultimate@gmail.com)

Hello!

I want help with Spanish. I´m native speaker. 
my email: hola@carlosalba.net

Regards!

**Comment by lucferre** [comment]
Hi, I want to help translate the site into Spanish.
Regards

**Comment by SachaG** [comment]
See here for future discussions about translations: https://github.com/StateOfJS/Translations/issues/1
