### ISSUE TITLE
What is the proper way to load an extra CSS file?

### ISSUE THREAD

**Issue by Goudarz** [StateOfJS/StateOfCSS-2019#43]
I am working on translation to Persian, which is Right-to-left language. For that, I need to customize the CSS to load the pages in the proper format.

**Comment by SachaG** [comment]
Oh right. I think maybe we can just load that file all the time, but add the current locale as a class to the body or the main wrapper to scope all styles?

**Comment by Goudarz** [comment]
I want to put the `rtl.css` file in the `head` tag.
